# Generated by Django 2.0 on 2018-01-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='test',
        ),
    ]
