# Generated by Django 2.0 on 2018-01-31 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0002_auto_20180130_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_list',
            fields=[
                ('card_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='card_list',
            name='card_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.store'),
        ),
        migrations.AddField(
            model_name='card_list',
            name='card_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.user'),
        ),
    ]
