# Generated by Django 2.0 on 2018-01-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0003_auto_20180131_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='card_list',
            new_name='card',
        ),
    ]
