# Generated by Django 2.0 on 2018-01-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0004_auto_20180131_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goods_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_message', models.TextField()),
                ('goods_price', models.FloatField()),
                ('goods_score', models.FloatField()),
                ('goods_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('order_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.goods')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_discount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='store_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_openId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.store'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.store'),
        ),
    ]
