# Generated by Django 2.0 on 2018-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0005_auto_20180131_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_buyer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_coment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='store',
            name='store_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='store_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
