# Generated by Django 2.0 on 2018-01-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0006_auto_20180131_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
