# Generated by Django 2.0 on 2018-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0007_auto_20180131_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='', max_length=50, verbose_name='商店名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
    ]
