# Generated by Django 2.0 on 2018-01-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0008_auto_20180131_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='卡号'),
        ),
    ]
