# Generated by Django 2.0 on 2018-02-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0009_auto_20180131_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_buyer',
            field=models.IntegerField(default=0, verbose_name='购买人数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.FloatField(default=0.0, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0.0, verbose_name='成交价格'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='商店id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_score',
            field=models.FloatField(default=0.0, verbose_name='商店分数'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(default='', max_length=50, verbose_name='商店类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='', max_length=50, verbose_name='联系方式'),
        ),
    ]
