# Generated by Django 2.0 on 2018-02-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0010_auto_20180201_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('comment_time', models.DateTimeField(verbose_name='评论时间')),
                ('comment_score', models.FloatField(default=0.0, verbose_name='评分')),
                ('comment_message', models.FloatField(default=0.0, verbose_name='评论内容')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='入库单号')),
                ('stock_price', models.FloatField(default=0, verbose_name='入库商品价格')),
                ('stock_number', models.IntegerField(default=0, verbose_name='入库数量')),
                ('stock_time', models.DateTimeField(verbose_name='入库日期')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_coment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_score',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_Allowsale',
            field=models.IntegerField(default=0, verbose_name='是否能销售'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_left',
            field=models.IntegerField(default=0, verbose_name='剩余数量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_plan',
            field=models.IntegerField(default=0, verbose_name='计划进货数量'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goosd_warn',
            field=models.IntegerField(default=0, verbose_name='库存预警数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.FloatField(default=0, verbose_name='折扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default='2018-02-01', verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.IntegerField(default=0, verbose_name='已购数量'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bishe.order'),
        ),
    ]
