# Generated by Django 2.0 on 2018-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0011_auto_20180201_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='会员卡号'),
        ),
    ]
