# Generated by Django 2.0 on 2018-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0012_auto_20180201_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default='2018-02-01', verbose_name='成交时间'),
        ),
    ]
