# Generated by Django 2.0 on 2018-02-01 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0014_auto_20180201_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 23, 39, 25, 629998), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.TextField(default='', max_length=50),
        ),
    ]
