# Generated by Django 2.0 on 2018-02-01 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0015_auto_20180201_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 23, 40, 59, 467093), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
