# Generated by Django 2.0 on 2018-02-01 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0016_auto_20180201_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 23, 41, 35, 81211), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
    ]
