# Generated by Django 2.0 on 2018-02-01 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0018_auto_20180201_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 23, 42, 54, 916428), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
