# Generated by Django 2.0 on 2018-02-02 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0020_auto_20180202_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 14, 4, 26, 87501), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 14, 4, 26, 101610), verbose_name='成交时间'),
        ),
    ]
