# Generated by Django 2.0 on 2018-02-02 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0021_auto_20180202_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 14, 5, 39, 354154), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 14, 5, 39, 350152), verbose_name='注册时间'),
        ),
    ]
