# Generated by Django 2.0 on 2018-02-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0023_auto_20180206_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='count',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_comment',
        ),
        migrations.AddField(
            model_name='store',
            name='store_date',
            field=models.TextField(default='', editable=False, verbose_name='商店成立时间'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 20, 25, 10, 278359), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_discount',
            field=models.FloatField(default=1, verbose_name='会员折扣'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='会员id'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=0, editable=False, max_length=50, verbose_name='会员卡号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_message',
            field=models.TextField(default='', verbose_name='商品信息'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_score',
            field=models.FloatField(default=0.0, verbose_name='商品分数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 20, 25, 10, 278359), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='入库单号'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.TextField(default='', verbose_name='商店地址'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='商店id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_message',
            field=models.TextField(default='', verbose_name='商店经营类型'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='商店名'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_phone',
            field=models.CharField(default='', max_length=20, verbose_name='商店联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_openId',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='用户openid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.TextField(default='', editable=False, max_length=50, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 20, 25, 10, 278359), editable=False, verbose_name='注册时间'),
        ),
    ]
