# Generated by Django 2.0 on 2018-02-06 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0025_auto_20180206_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_password',
            field=models.TextField(default='', editable=False, max_length=50, verbose_name='商店密码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 20, 44, 31, 732995), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 20, 44, 31, 732995), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 20, 44, 31, 732995), editable=False, verbose_name='注册时间'),
        ),
    ]
