# Generated by Django 2.0 on 2018-02-08 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0026_auto_20180206_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 13, 33, 7, 817324), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 13, 33, 7, 817324), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 13, 33, 7, 817324), editable=False, verbose_name='注册时间'),
        ),
    ]
