# Generated by Django 2.0 on 2018-02-08 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0027_auto_20180208_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 13, 33, 53, 383140), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_score',
            field=models.FloatField(default=2.0, verbose_name='商店分数'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 13, 33, 53, 367537), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 13, 33, 53, 367537), editable=False, verbose_name='注册时间'),
        ),
    ]
