# Generated by Django 2.0 on 2018-02-08 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0029_auto_20180208_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_registerId',
            field=models.IntegerField(default=0, max_length=50, verbose_name='社会信用号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 20, 16, 24, 436729), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 20, 16, 24, 436729), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 20, 16, 24, 436729), editable=False, verbose_name='注册时间'),
        ),
    ]
