# Generated by Django 2.0 on 2018-02-08 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0032_auto_20180208_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 21, 40, 38, 470347), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.TextField(default='', editable=False, max_length=50, verbose_name='商店名'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 21, 40, 38, 470347), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(default='', editable=False, max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 21, 40, 38, 470347), editable=False, verbose_name='注册时间'),
        ),
    ]
