# Generated by Django 2.0 on 2018-02-09 06:13

import bishe.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0038_auto_20180208_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_cover',
            field=models.ImageField(default='storeImage/default.png', upload_to=bishe.models.get_path, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_img1',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片1'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_img2',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_img3',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 14, 13, 24, 476738), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 14, 13, 24, 476738), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='userImage/default.png', upload_to='userImage', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 14, 13, 24, 476738), editable=False, verbose_name='注册时间'),
        ),
    ]
