# Generated by Django 2.0 on 2018-02-09 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0050_auto_20180209_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 36, 37, 369036), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 36, 37, 369036), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 36, 37, 369036), editable=False, verbose_name='注册时间'),
        ),
    ]
