# Generated by Django 2.0 on 2018-02-09 11:23

import bishe.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0056_auto_20180209_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 19, 23, 46, 199636), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_cover',
            field=models.ImageField(default='storeImage/default.png', upload_to=bishe.models.get_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 19, 23, 46, 199636), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 19, 23, 46, 184012), editable=False, verbose_name='注册时间'),
        ),
    ]
