# Generated by Django 2.0 on 2018-02-22 05:21

import bishe.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0057_auto_20180209_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_img1',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片1'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_img2',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_img3',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片3'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_img4',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片4'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_img5',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片5'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 13, 21, 41, 761995), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img1',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img2',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_img3',
            field=models.ImageField(blank=True, upload_to=bishe.models.get_path, verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 13, 21, 41, 761995), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 13, 21, 41, 761995), editable=False, verbose_name='注册时间'),
        ),
    ]
