# Generated by Django 2.0 on 2018-02-22 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0058_auto_20180222_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='store_registerId',
            field=models.CharField(default=0, max_length=50, verbose_name='社会信用号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 13, 23, 59, 13870), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 13, 23, 58, 998262), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 13, 23, 58, 998262), editable=False, verbose_name='注册时间'),
        ),
    ]
