# Generated by Django 2.0 on 2018-02-22 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0059_auto_20180222_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_score',
            field=models.FloatField(default=2.0, verbose_name='商品分数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 21, 5, 12, 437123), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 21, 5, 12, 421515), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 21, 5, 12, 421515), editable=False, verbose_name='注册时间'),
        ),
    ]
