# Generated by Django 2.0 on 2018-02-22 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0060_auto_20180222_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_left',
            field=models.FloatField(default=0, verbose_name='剩余数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.FloatField(default=0, verbose_name='已购数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_plan',
            field=models.FloatField(default=0, verbose_name='计划进货数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goosd_warn',
            field=models.FloatField(default=0, verbose_name='库存预警数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 21, 53, 17, 67775), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 21, 53, 17, 67775), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 21, 53, 17, 67775), editable=False, verbose_name='注册时间'),
        ),
    ]
