# Generated by Django 2.0 on 2018-02-22 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0062_auto_20180222_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goosd_warn',
            new_name='goods_warn',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 23, 51, 42, 570334), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 23, 51, 42, 570334), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 23, 51, 42, 570334), editable=False, verbose_name='注册时间'),
        ),
    ]
