# Generated by Django 2.0 on 2018-03-04 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0064_auto_20180223_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_img',
            field=models.ImageField(default='card/default.png', upload_to='', verbose_name='会员卡条形码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 47, 29, 286193), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 47, 29, 286193), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 47, 29, 286193), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 47, 29, 286193), editable=False, verbose_name='注册时间'),
        ),
    ]
