# Generated by Django 2.0 on 2018-03-05 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0065_auto_20180304_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_score',
            field=models.FloatField(default=0, verbose_name='会员卡积分'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_discount',
            field=models.FloatField(default=1.0, verbose_name='折扣价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 25, 45, 938298), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 25, 45, 938298), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 25, 45, 938298), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 25, 45, 922673), editable=False, verbose_name='注册时间'),
        ),
    ]
