# Generated by Django 2.0 on 2018-03-05 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0066_auto_20180305_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_discount',
            field=models.FloatField(default=1, verbose_name='初始折扣'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 48, 58, 613656), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 48, 58, 613656), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 48, 58, 613656), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 48, 58, 613656), editable=False, verbose_name='注册时间'),
        ),
    ]
