# Generated by Django 2.0 on 2018-03-05 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0067_auto_20180305_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_img',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 20, 30, 18, 486063), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 20, 30, 18, 486063), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 20, 30, 18, 486063), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 20, 30, 18, 486063), editable=False, verbose_name='注册时间'),
        ),
    ]
