# Generated by Django 2.0 on 2018-03-05 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0068_auto_20180305_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_goods',
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='USER2ORDER', to='bishe.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STORE2CARD', to='bishe.store'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USER2CARD', to='bishe.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ORDER2COMENT', to='bishe.order'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STORE2GOODS', to='bishe.store'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_goods',
        ),
        migrations.AddField(
            model_name='order',
            name='order_goods',
            field=models.ManyToManyField(related_name='GOODS2ORDER', to='bishe.goods'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STORE2ORDER', to='bishe.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 21, 6, 23, 80012), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GOODS2STOCK', to='bishe.goods'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 21, 6, 23, 80012), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 21, 6, 23, 80012), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 21, 6, 23, 80012), editable=False, verbose_name='注册时间'),
        ),
    ]
