# Generated by Django 2.0 on 2018-03-14 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0069_auto_20180305_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_card_count',
            field=models.IntegerField(default=0, verbose_name='会员数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 36, 25, 722899), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 36, 25, 724900), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 36, 25, 719896), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 36, 25, 718894), editable=False, verbose_name='注册时间'),
        ),
    ]
