# Generated by Django 2.0 on 2018-03-14 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0070_auto_20180314_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_card_count',
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_number',
            field=models.IntegerField(default=0, verbose_name='会员数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 38, 6, 518710), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 38, 6, 520712), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 38, 6, 514708), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 38, 6, 513707), editable=False, verbose_name='注册时间'),
        ),
    ]
