# Generated by Django 2.0 on 2018-03-14 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0071_auto_20180314_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_card_api',
            field=models.TextField(default='', verbose_name='会员卡获取api'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_style',
            field=models.IntegerField(default=0, verbose_name='会员卡号类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 21, 3, 48, 839805), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 21, 3, 48, 841822), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 21, 3, 48, 836803), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 21, 3, 48, 835802), editable=False, verbose_name='注册时间'),
        ),
    ]
