# Generated by Django 2.0 on 2018-03-14 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0073_auto_20180314_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_discount',
            new_name='store_card_Ddiscount',
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_Dlever',
            field=models.CharField(default='', max_length=50, verbose_name='初始等级'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_date',
            field=models.TextField(default=0, verbose_name='有限期'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_level',
            field=models.TextField(default=0, verbose_name='会员等级划分'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_message',
            field=models.TextField(default='', verbose_name='会员卡说明'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_card_up_style',
            field=models.IntegerField(default=0, verbose_name='等级上升的标准'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Daddress',
            field=models.TextField(blank=True, verbose_name='默认收货地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Dphone',
            field=models.IntegerField(default=0, verbose_name='收货电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.IntegerField(default=0, verbose_name='默认地址和电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 5, 41, 376392), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 5, 41, 380415), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 5, 41, 373390), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 5, 41, 373390), editable=False, verbose_name='注册时间'),
        ),
    ]
