# Generated by Django 2.0 on 2018-03-14 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0074_auto_20180314_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_favourite',
            field=models.ManyToManyField(related_name='STORE2USER', to='bishe.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 13, 8, 727443), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 13, 8, 730445), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 13, 8, 724441), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 23, 13, 8, 722439), editable=False, verbose_name='注册时间'),
        ),
    ]
