# Generated by Django 2.0 on 2018-03-17 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0076_auto_20180317_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_Allowcard',
            field=models.IntegerField(default=0, verbose_name='是否能会员卡打折'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_cardScore',
            field=models.FloatField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 21, 17, 25, 999148), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 21, 17, 25, 999148), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 21, 17, 25, 983523), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 21, 17, 25, 983523), editable=False, verbose_name='注册时间'),
        ),
    ]
