# Generated by Django 2.0 on 2018-03-17 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0077_auto_20180317_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 22, 12, 3, 972363), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 22, 12, 3, 972363), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_card_up_style',
            field=models.TextField(default=0, verbose_name='等级上升的标准'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 22, 12, 3, 972363), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 22, 12, 3, 972363), editable=False, verbose_name='注册时间'),
        ),
    ]
