# Generated by Django 2.0 on 2018-03-17 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0078_auto_20180317_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_level',
            field=models.CharField(default='', max_length=50, verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 23, 26, 21, 300308), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 23, 26, 21, 300308), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 23, 26, 21, 300308), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 23, 26, 21, 300308), editable=False, verbose_name='注册时间'),
        ),
    ]
