# Generated by Django 2.0 on 2018-03-18 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0079_auto_20180317_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 19, 22, 171550), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 19, 22, 171550), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_card_prefix',
            field=models.CharField(default='', max_length=50, verbose_name='会员卡前缀'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 19, 22, 171550), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 19, 22, 171550), editable=False, verbose_name='注册时间'),
        ),
    ]
