# Generated by Django 2.0 on 2018-03-18 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishe', '0080_auto_20180318_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 33, 12, 998074), verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 33, 12, 998074), verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_card_number',
            field=models.CharField(default=0, max_length=50, verbose_name='会员数量'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 33, 12, 998074), editable=False, verbose_name='商店注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 22, 33, 12, 998074), editable=False, verbose_name='注册时间'),
        ),
    ]
